services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:16.2-alpine3.19'
    env_file:
      - '.env'
    ports:
      - '5432:5432'
  redis:
    container_name: 'redis'
    image: 'redis:6.2'
    ports:
      - '6379:6379'
