name: Dev CI

on:
  push:
    branches: [ main,dev ]
  pull_request:
    branches: [ main,dev ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: local_db_test
      DB_USER: local_user
      DB_PASSWORD: local_password

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Apt-get update
      run: sudo apt-get update

    - name: Set up config
      run: cp .env.example .env

    - name: Install POSTGRESQL
      run: sudo apt-get install -y postgresql postgresql-contrib

    - name: Set up POSTGRESQL
      run: |
        sudo /etc/init.d/postgresql start
        sudo -u postgres psql -c "CREATE USER ${{ env.DB_USER }} WITH PASSWORD '${{ env.DB_PASSWORD }}';"
        sudo -u postgres psql -c "CREATE DATABASE ${{ env.DB_DATABASE }} OWNER ${{ env.DB_USER }};"

    - name: Install redis
      run: sudo apt-get install -y redis-tools redis-server

    - name: Set up Redis
      run: sudo /etc/init.d/redis-server start

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build

    - name: Run linter
      run: npm run lint

    - name: Run migration
      run: npm run migration:run

    - name: Run tests
      run: npm run tests
