name: Dev CI

on:
  push:
    branches: [ main,dev ]
  pull_request:
    branches: [ main,dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DB_DATABASE: local_db
      DB_USER: local_user
      DB_PASSWORD: local_password

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Apt-get update
      run: sudo apt-get update

    - name: Set up config
      run: cp .env.example .env

    - name: Set up MySQL
      run: npm run services:up

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

    - name: Run build
      run: npm run build

    - name: Run migration
      run: npm run migration:run

    - name: Run tests
      run: npm run test
